// Auto-generated by SoundBankEditor. Do not modify manually.
public enum 
{
    MenuToggleMiniGame,
    MenuToggleDevTool,
    MenuChangeSuccess,
    MenuClosing,
    BuySound,
    BuyFailSound,
    WinChess,
    LoseChess,
    ChessMovePiece,
    ChessCapturePiece,
    ChessCheck,
    ChessCastle,
}
