// Auto-generated by SoundBankEditor. Do not modify manually.
using System.Collections.Generic;
public static class MusicsLookup_Generated
{
    public static readonly Dictionary<Musics, string> IdToGuid = new()
    {
        { Musics.MainMusic, "719d7fd7-afb8-4630-a32f-60596110c5ec" },
        { Musics.GameMusic, "0d6f3e0d-f8d7-4f68-8ab9-79c3a7d98cf4" },
    };
}
