// Auto-generated by SoundBankEditor. Do not modify manually.
public enum SoundName
{
    MenuToggleMiniGame,
    MenuToggleDevTool,
    MenuChangeSuccess,
    MenuClosing,
    BuySound,
    BuyFailSound,
}
