// Auto-generated by SoundMasterEditor. Do not modify manually.
namespace WolfheatProductions.SoundMaster
{
    public enum SoundName
    {
        MenuToggleMiniGame,
        MenuToggleDevTool,
        MenuChangeSuccess,
        MenuClosing,
        BuySound,
        BuyFailSound,
        WinChess,
        LoseChess,
        ChessMovePiece,
        ChessCapturePiece,
        ChessCheck,
        ChessCastle,
    }

    public enum MusicName
    {
        MainMusic,
        GameMusic,
    }
}
