// Auto-generated by SoundBankEditor. Do not modify manually.
using System.Collections.Generic;
public static class SoundLookup_Generated
{
    public static readonly Dictionary<SoundName, string> IdToGuid = new()
    {
        { SoundName.MenuToggleMiniGame, "b88e19e4-03c6-4385-b04e-3c98f9de2835" },
        { SoundName.MenuToggleDevTool, "5ca19dc3-1258-485c-8c99-4739d3dddcef" },
        { SoundName.MenuChangeSuccess, "f6cc5e12-77ff-45f0-ba54-ddf8a28ddd19" },
        { SoundName.MenuClosing, "5abc9695-8fa1-4acc-bc6d-d6a65bd1b33f" },
        { SoundName.BuySound, "42f9b8c5-9f7c-41fe-9cf1-4db8b955fa84" },
        { SoundName.BuyFailSound, "6b7799ec-6872-4678-8be2-c5085d7c0254" },
    };
}
