// Auto-generated by SoundBankEditor. Do not modify manually.
using System.Collections.Generic;
public static class SoundLookup
{
    public static readonly Dictionary<SoundID, string> IdToGuid = new()
    {
        { SoundID.MenuClick, "b88e19e4-03c6-4385-b04e-3c98f9de2835" },
        { SoundID.MenuClose, "5ca19dc3-1258-485c-8c99-4739d3dddcef" },
    };
}
